---

- name: Check key variables
  ansible.builtin.assert:
    that:
    - keycloak_server_url | string | length > 0

# Create the namespace and other basic materials

- name: Create namespace ({{ ui_namespace }})
  k8s:
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
    wait: yes

- name: Create DockerHub image pull secret
  k8s:
    definition: "{{ lookup('template', 'secret-dh-imagepull.yaml.j2') }}"
    wait: yes
  vars:
    pull_namespace: "{{ ui_namespace }}"
    pull_secret: "{{ ui_dockerhub_pullsecret }}"
  when: ui_dockerhub_pullsecret | string | length > 0

- name: Create namespace material
  k8s:
    definition: "{{ lookup('template', item) }}"
    wait: yes
  loop:
  - serviceaccount.yaml.j2

# Deploy the application...

- name: Deploy application
  k8s:
    definition: "{{ lookup('template', item) }}"
    wait: yes
    wait_timeout: "{{ pod_ready_timeout }}"
  loop:
  - configmap.yaml.j2
  - deployment.yaml.j2
  - service.yaml.j2
  - ingress.yaml.j2
