---

- name: Prep
  ansible.builtin.include_tasks: prep.yaml
  vars:
    kubeconfig: "{{ ui_kubeconfig }}"

# The 'installation' must also be set.

- name: Assert installation name is defined
  ansible.builtin.assert:
    that:
    - ui_installation_name | string | length > 0
    - ui_installation_name != 'SetMe'
    msg: "You must define 'ui_installation_name'"

# Include sensitive (Ansible Vault) variables based on the installation name.
# We include 'sensitive-local.vault' variables if the installation name is 'local'.
# The user will need to provide the vault password.

- name: Include sensitive (vault) variables ({{ ui_installation_name }})
  ansible.builtin.include_vars:
    file: sensitive-{{ ui_installation_name }}.vault
  when: ui_installation_name | length > 0

# Go...

- name: Deploy via Host and API
  module_defaults:
    group/k8s:
      host: "{{ k8s_auth_host }}"
      api_key: "{{ k8s_auth_api_key }}"
      kubeconfig: "{{ ui_kubeconfig }}"
  block:

  - name: Deploy (API)
    ansible.builtin.include_tasks: deploy.yaml
    when: ui_state | string == 'present'

  - name: Undeploy (API)
    ansible.builtin.include_tasks: undeploy.yaml
    when: ui_state | string == 'absent'
