---

# Commonly adjusted application variables -
# everything we expect the user to consider changing.
# To avoid clutter, put less-common variables in 'vars/main.yaml'

# Set to 'absent' to undeploy
ui_state: present

# The namespace to create for application deployment.
ui_namespace: data-manager-ui

# The 'installation' name. This is used to uniquely identify the UI for a
# specific customer. It is used by the playbook to load customer-specific variables,
# which are encoded in sensitive ('.vault') files that are located in the
# role's 'vars' directory. Variables are loaded into an 'installation' root variable
# so the variable 'replicas' will be available to the playbook as
# 'installation.replicas'. To load the variables the user will also need to provide
# the playbook with the vault password.
ui_installation_name: SetMe

# Message of the day (YAML) - a list (possibly empty).
# This gets injected into the UI Pod as the 'motd.yaml' file.
ui_motd: |
  motd: []

# Realm
ui_keycloak_realm: squonk
ui_keycloak_client_id: data-manager-ui
ui_keycloak_client_secret: SetMe
# The application auth0 secret.
# Basically a 32-character hex string.
ui_auth0_secret: "{{ lookup('password', '/dev/null length=32 chars=hexdigits') }}"
# The sentry token, blank if not required.
ui_sentry_auth_token: ''

# Details of the application container image
ui_image_name: informaticsmatters/squonk2-data-manager-ui
ui_image_tag: 'latest'

# The ingress hostname (http/https assumed) and path
ui_hostname: squonk.it
ui_hostname_path: data-manager-ui
# The ingress "let's Encrypt" certificate issuer.
# One of 'production' or 'staging'
ui_cert_issuer: production
# And the maximum size of a body for an upload.
# '0' implies unlimited, nginx default is typically 1m.
# Part of the nginx ingress.
ui_ingress_proxy_body_size: 100m

# The Data Tier URL (https:// assumed)
ui_data_manager_api_address: squonk.it/data-manager-api
# The Account Server URL (https:// assumed)
ui_account_server_api_address: squonk.it/account-server-api

# A pull-secret for public images pulled from DockerHub.
# If set this is the base-64 string that can be used as the value
# in our Kubernetes Secret as the .dockerconfigjson value.
# If set it is applied to the ServiceAccount in the namespace
# and applied to Pods that use that namespace.
ui_dockerhub_pullsecret: ''

## Provided by our chosen AWX/Tower Keycloak credentials
# (keycloak credential type)...

# The KEYCLOAK_SERVER_URL value injected by the AWX credential
# has a 'https://` prefix and '/auth' suffix. So a host at
# example.com will be injected as 'https://example.com/auth'.
# The user can provide their own value directly if required.
keycloak_server_url: "{{ lookup('env', 'KEYCLOAK_SERVER_URL') }}"

# Number of UI Pod replicas
ui_replicas: 1

# The Pod priority class,
# not set if blank.
ui_priority_class: ''

# If set, use this kubernetes config, rather than K8S credentials.
# You would set this if executing the playbooks locally, i.e. not from
# and AWX server, where K8S_AUTH_HOST, K8S_AUTH_API_KEY environment
# variables are set and used.
ui_kubeconfig: ''
