---

# Commonly adjusted application variables -
# everything we expect the user to consider changing.
# To avoid clutter, put less-common variables in 'vars/main.yaml'

# Set to 'absent' to undeploy
maui_state: present

# The namespace to create for application deployment.
maui_namespace: data-manager-ui

# Realm
maui_keycloak_realm: squonk
maui_keycloak_client_id: data-manager-ui
maui_keycloak_client_secret: SetMe
# The application auth0 secret.
# Basically a 32-character heck string.
maui_auth0_secret: "{{ lookup('password', '/dev/null length=32 chars=hexdigits') }}"
# The sentry token, blank if not required.
maui_sentry_auth_token: ''

# Details of the application container image
maui_image_name: informaticsmatters/squonk2-data-manager-ui
maui_image_tag: 'latest'

# The ingress hostname (http/https assumed) and path
maui_hostname: squonk.it
maui_hostname_path: data-manager-ui
# The ingress "let's Encrypt" certificate issuer.
# One of 'production' or 'staging'
maui_cert_issuer: production
# And the maximum size of a body for an upload.
# '0' implies unlimited, nginx default is typically 1m.
# Part of the nginx ingress.
maui_ingress_proxy_body_size: 100m

# The Data Tier URL (https:// assumed)
maui_data_manager_api_address: squonk.it/data-manager-api
# The Account Server URL (https:// assumed)
maui_account_server_api_address: squonk.it/account-server-api

# A pull-secret for public images pulled from DockerHub.
# If set this is the base-64 string that can be used as the value
# in our Kubernetes Secret as the .dockerconfigjson value.
# If set it is applied to the ServiceAccount in the namespace
# and applied to Pods that use that namespace.
maui_dockerhub_pullsecret: ''

## Provided by our chosen AWX/Tower Keycloak credentials
# (keycloak credential type)...

# The KEYCLOAK_SERVER_URL value injected by the AWX credential
# has a 'https://` prefix and '/auth' suffix. So a host at
# example.com will be injected as 'https://example.com/auth'.
# The user can provide their own value directly if required.
keycloak_server_url: "{{ lookup('env', 'KEYCLOAK_SERVER_URL') }}"

# Number of UI Pod replicas
maui_replicas: 1

# The Pod priority class,
# not set if blank.
maui_priority_class: ''

# If set, use this kubernetes config, rather than K8S credentials.
# You would set this if executing the playbooks locally, i.e. not from
# and AWX server, where K8S_AUTH_HOST, K8S_AUTH_API_KEY environment
# variables are set and used.
maui_kubeconfig: ''
