---

# Less commonly application variables -
# things the user is less-like to want to change (but can).
# This is here to avoid clutter in 'defaults/main.yaml'

# The application Pod Security Policy (PSP)
maui_sa_psp: im-core-unrestricted

# Set to disable SSL certificate checks
maui_disable_ssl_cert_check: no

# Application CPU and Memory requests and limits.
# Requests are required but limits are not.
# Set limit to blank ('') or zero to avoid a limit.
maui_cpu_request: 500m
maui_cpu_limit: 4
maui_mem_request: 250Mi
maui_mem_limit: 0

# A fallback node-selector key.
# Some deployments have other labels as selectors.
# If they're not present the deployment should use this.
maui_fallback_node_selector_key: informaticsmatters.com/purpose-application

# Do we need to add kubernetes modules?
# On some older AWX servers we do.
maui_control_needs_kubernetes: no

# General variables

wait_timeout: 120
pod_ready_timeout: 600
