---

# Less commonly application variables -
# things the user is less-like to want to change (but can).
# This is here to avoid clutter in 'defaults/main.yaml'

# The application Pod Security Policy (PSP)
maui_sa_psp: im-core-unrestricted

# Application CPU and Memory requests and limits.
# Requests are required but limits are not.
# Set limit to blank ('') to avoid a limit.
maui_cpu_request: 500m
maui_cpu_limit: 1
maui_mem_request: 250Mi
maui_mem_limit: 2Gi

# General variables

wait_timeout: 120
pod_ready_timeout: 600
